### ISSUE TITLE
ark doesn't automatically figure out version from url (or: documentation is misleading)

### ISSUE THREAD

**Issue by iancward** [sous-chefs/ark#198]
### Cookbook version
3.1.0

### Chef-client version
13.3.42 via test-kitchen 1.16.0

### Platform Details
Workstation: Fedora 25; test kitchen instance: RHEL 7.2 running in OpenStack

### Scenario:
The [Overview documentation](https://github.com/chef-cookbooks/ark#overview) seems to imply that using a version in the `ark` resource declaration isn't necessary and that the cookbook will figure out what the artifact version is in the URL.

### Steps to Reproduce:
Declare an `ark` resource:
```ruby
ark 'myapp' do
  url https://my.artifact.repository/myapp/110/myapp-110.zip
  prefix_root '/usr/local/myapp'
  home_dir '/usr/local/myapp/current'
end
```

### Expected Result:
Based on the fact that the overview documentation doesn't use the `version` property and claims that the artifact will be extracted to a version-specific directory, I expected to not need to use the version property and have ark figure out what the version is.

### Actual Result:
The application is deployed to `/usr/local/myapp/myapp-1` and if you change the artifact URL (say, to deploy myapp-111) ark doesn't do anything because `myapp-1` already exists.

Our artifact repository tool allows you to search for artifacts (e.g. to use keywords to fetch the most recent artifact) and the search endpoint returns a HTTP redirect to the actual artifact. I build a library to use `net/http` to hit the search endpoint with the right http query parameters, and I'm taking the result and putting it into the `url` property of the `ark` resource.

**Comment by qubitrenegade** [comment]
what version is 110? or 111?  This does not appear to follow any versioning standard I'm aware of...

did you try `https://my.artifact.repository/myapp/v1.1.0/myapp-v1.1.0.zip` or maybe just `https://my.artifact.repository/myapp/1.1.0/myapp-1.1.0.zip`

Ok, so:

[this is why you're getting `package-1`](https://github.com/chef-cookbooks/ark/blob/master/libraries/resource_defaults.rb#L92-L94)

[According to this](https://github.com/chef-cookbooks/ark/blob/master/spec/libraries/resource_defaults_spec.rb#L124-L140)

`Ark::ResourceDefaults` is 1... unless we set it...

Now, maybe Ark tries to figure it out first then if it can't it dies at 1...

But where would the heuristics for that be?  Here's the other interesting mentions of version (i.e. not tests) ([full search](https://github.com/chef-cookbooks/ark/search?utf8=%E2%9C%93&q=version&type=)]

https://github.com/chef-cookbooks/ark/blob/master/libraries/default.rb#L51
https://github.com/chef-cookbooks/ark/blob/master/libraries/resource_defaults.rb#L24-L26
https://github.com/chef-cookbooks/ark/blob/master/resources/default.rb#L38

I mean, to me it looks like, unless there's some magic in [`property :version, String`](https://github.com/chef-cookbooks/ark/blob/master/resources/default.rb#L38) I don't see any version heuristics... so yea, 1 is the default unless you specify it.
