### ISSUE TITLE
v5.1.0 tagged incorrectly?

### ISSUE THREAD

**Issue by hrak** [sous-chefs/ark#231]
## :ghost: Brief Description

Not sure if this is intentional or not, but version 5.1.0 is tagged as `5.1.0` instead of `v5.1.0` like all previous releases.

## :pancakes: Cookbook version

5.1.0

**Comment by ramereth** [comment]
@hrak our new automated release system doesn't include the `v` in the tags so it's intentional. You can blame @Xorima for that :laughing:
